//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class access_levels
    {
        public int id { get; set; }
        public string module_name { get; set; }
        public int min_access { get; set; }
        public int avg_access { get; set; }
        public int max_access { get; set; }
        public int sratus { get; set; }
    }
}
