//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aco
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string model { get; set; }
        public Nullable<int> foreign_key { get; set; }
        public string alias { get; set; }
        public Nullable<int> lft { get; set; }
        public Nullable<int> rght { get; set; }
    }
}
