//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminpushnotification
    {
        public int id { get; set; }
        public int device_type { get; set; }
        public string device_id { get; set; }
        public string device_token { get; set; }
        public string status { get; set; }
    }
}
