//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class appsterEntities : DbContext
    {
        public appsterEntities()
            : base("name=appsterEntities")
        {
            this.Database.CommandTimeout = 180;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<access_levels> access_levels { get; set; }
        public virtual DbSet<adminpushnotification> adminpushnotifications { get; set; }
        public virtual DbSet<chat> chats { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<follow> follows { get; set; }
        public virtual DbSet<gift_categories> gift_categories { get; set; }
        public virtual DbSet<gift> gifts { get; set; }
        public virtual DbSet<leaderboard> leaderboards { get; set; }
        public virtual DbSet<ledger_shares> ledger_shares { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<post_likes> post_likes { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vipgift> vipgifts { get; set; }
        public virtual DbSet<vipgiftssend> vipgiftssends { get; set; }
        public virtual DbSet<wall> walls { get; set; }
        public virtual DbSet<aco> acos { get; set; }
        public virtual DbSet<admin_histories> admin_histories { get; set; }
        public virtual DbSet<aro> aros { get; set; }
        public virtual DbSet<aros_acos> aros_acos { get; set; }
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<cash_backs> cash_backs { get; set; }
        public virtual DbSet<chat_deletes> chat_deletes { get; set; }
        public virtual DbSet<checkin_users> checkin_users { get; set; }
        public virtual DbSet<cost_settings> cost_settings { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<credit> credits { get; set; }
        public virtual DbSet<custom_pages> custom_pages { get; set; }
        public virtual DbSet<device_saves> device_saves { get; set; }
        public virtual DbSet<event_categories> event_categories { get; set; }
        public virtual DbSet<event_participants> event_participants { get; set; }
        public virtual DbSet<event_votes> event_votes { get; set; }
        public virtual DbSet<event_voting_lists> event_voting_lists { get; set; }
        public virtual DbSet<faq> faqs { get; set; }
        public virtual DbSet<leaderboard_activations> leaderboard_activations { get; set; }
        public virtual DbSet<leaderboard_logs> leaderboard_logs { get; set; }
        public virtual DbSet<leaderboard_temps> leaderboard_temps { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<ofConversation> ofConversations { get; set; }
        public virtual DbSet<ofExtComponentConf> ofExtComponentConfs { get; set; }
        public virtual DbSet<ofGroup> ofGroups { get; set; }
        public virtual DbSet<ofGroupProp> ofGroupProps { get; set; }
        public virtual DbSet<ofGroupUser> ofGroupUsers { get; set; }
        public virtual DbSet<ofID> ofIDs { get; set; }
        public virtual DbSet<ofMucAffiliation> ofMucAffiliations { get; set; }
        public virtual DbSet<ofMucMember> ofMucMembers { get; set; }
        public virtual DbSet<ofMucRoom> ofMucRooms { get; set; }
        public virtual DbSet<ofMucRoomProp> ofMucRoomProps { get; set; }
        public virtual DbSet<ofMucService> ofMucServices { get; set; }
        public virtual DbSet<ofMucServiceProp> ofMucServiceProps { get; set; }
        public virtual DbSet<ofOffline> ofOfflines { get; set; }
        public virtual DbSet<ofPresence> ofPresences { get; set; }
        public virtual DbSet<ofPrivacyList> ofPrivacyLists { get; set; }
        public virtual DbSet<ofPrivate> ofPrivates { get; set; }
        public virtual DbSet<ofProperty> ofProperties { get; set; }
        public virtual DbSet<ofPubsubAffiliation> ofPubsubAffiliations { get; set; }
        public virtual DbSet<ofPubsubDefaultConf> ofPubsubDefaultConfs { get; set; }
        public virtual DbSet<ofPubsubItem> ofPubsubItems { get; set; }
        public virtual DbSet<ofPubsubNode> ofPubsubNodes { get; set; }
        public virtual DbSet<ofPubsubNodeJID> ofPubsubNodeJIDs { get; set; }
        public virtual DbSet<ofPubsubSubscription> ofPubsubSubscriptions { get; set; }
        public virtual DbSet<ofRemoteServerConf> ofRemoteServerConfs { get; set; }
        public virtual DbSet<ofRoster> ofRosters { get; set; }
        public virtual DbSet<ofRosterGroup> ofRosterGroups { get; set; }
        public virtual DbSet<ofRRD> ofRRDs { get; set; }
        public virtual DbSet<ofSASLAuthorized> ofSASLAuthorizeds { get; set; }
        public virtual DbSet<ofSecurityAuditLog> ofSecurityAuditLogs { get; set; }
        public virtual DbSet<ofUser> ofUsers { get; set; }
        public virtual DbSet<ofUserFlag> ofUserFlags { get; set; }
        public virtual DbSet<ofUserProp> ofUserProps { get; set; }
        public virtual DbSet<ofVCard> ofVCards { get; set; }
        public virtual DbSet<ofVersion> ofVersions { get; set; }
        public virtual DbSet<page> pages { get; set; }
        public virtual DbSet<paypal_settings> paypal_settings { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<save_push_notifications> save_push_notifications { get; set; }
        public virtual DbSet<send_gifts> send_gifts { get; set; }
        public virtual DbSet<test> tests { get; set; }
        public virtual DbSet<thank> thanks { get; set; }
        public virtual DbSet<top_ups> top_ups { get; set; }
        public virtual DbSet<verification> verifications { get; set; }
        public virtual DbSet<ofConParticipant> ofConParticipants { get; set; }
        public virtual DbSet<ofMessageArchive> ofMessageArchives { get; set; }
        public virtual DbSet<ofMucConversationLog> ofMucConversationLogs { get; set; }
        public virtual DbSet<ofPubsubNodeGroup> ofPubsubNodeGroups { get; set; }
        public virtual DbSet<schema_migrations> schema_migrations { get; set; }
    }
}
