//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aros_acos
    {
        public int id { get; set; }
        public int aro_id { get; set; }
        public int aco_id { get; set; }
        public string C_create { get; set; }
        public string C_read { get; set; }
        public string C_update { get; set; }
        public string C_delete { get; set; }
    }
}
