//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public int id { get; set; }
        public int status { get; set; }
        public System.DateTime created { get; set; }
        public string article_name_en { get; set; }
        public string article_image { get; set; }
        public string article_description_en { get; set; }
        public string article_name_sp { get; set; }
        public string article_description_sp { get; set; }
        public string article_name_zh { get; set; }
        public string article_description_zh { get; set; }
    }
}
