//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cash_backs
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int total_amount { get; set; }
        public int redeem_gold { get; set; }
        public int payment_type { get; set; }
        public string paypal_email { get; set; }
        public int account_number { get; set; }
        public string branch_code { get; set; }
        public string bank_name { get; set; }
        public int status { get; set; }
        public System.DateTime created { get; set; }
    }
}
