//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cost_settings
    {
        public int id { get; set; }
        public int cost_chatting { get; set; }
        public int cost_commenting { get; set; }
        public int chat_commision { get; set; }
        public int gift_commision { get; set; }
        public int refe_commision { get; set; }
        public string minimum_gold_limit { get; set; }
        public string minimum_bean_limit { get; set; }
        public string average_gold_limit { get; set; }
        public string average_bean_limit { get; set; }
        public string maximum_gold_limit { get; set; }
        public string maximum_bean_limit { get; set; }
        public decimal paypal_share { get; set; }
        public System.DateTime created { get; set; }
    }
}
