//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int gold { get; set; }
        public int bean { get; set; }
        public string remarks { get; set; }
        public int credit_type { get; set; }
    }
}
