//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int id { get; set; }
        public string event_name { get; set; }
        public int owner_id { get; set; }
        public string event_name_sp { get; set; }
        public string event_name_zh { get; set; }
        public string event_category { get; set; }
        public int event_vote_by { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime date { get; set; }
        public int days { get; set; }
        public string event_cost { get; set; }
        public int event_cost_type { get; set; }
        public string participation_cost { get; set; }
        public string event_price { get; set; }
        public int event_price_type { get; set; }
        public int price_given { get; set; }
        public int status { get; set; }
        public string event_uids { get; set; }
    }
}
