//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_participants
    {
        public int id { get; set; }
        public string event_id { get; set; }
        public string participant_id { get; set; }
        public int participant_media_type { get; set; }
        public string participant_up_photo { get; set; }
        public string participant_up_video { get; set; }
        public string cost { get; set; }
        public long vote_count { get; set; }
    }
}
