//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gift
    {
        public int id { get; set; }
        public int gift_category_id { get; set; }
        public string gift_name { get; set; }
        public int gift_weight { get; set; }
        public int cost_gold { get; set; }
        public int cost_bean { get; set; }
        public int receiver_gold { get; set; }
        public string image { get; set; }
        public string sp_sound { get; set; }
        public string zh_sound { get; set; }
        public string sound { get; set; }
        public string sp_gift_name { get; set; }
        public string zh_gift_name { get; set; }
        public int status { get; set; }
        public System.DateTime created { get; set; }
    }
}
