//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaderboard
    {
        public int id { get; set; }
        public string leaderboard_name { get; set; }
        public string leaderboard_name_sp { get; set; }
        public string leaderboard_name_zh { get; set; }
        public string leaderboard_category { get; set; }
        public int status { get; set; }
    }
}
