//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaderboard_logs
    {
        public int id { get; set; }
        public int leaderboard_id { get; set; }
        public int leaderboard_activation_id { get; set; }
        public int user_id { get; set; }
        public int count { get; set; }
        public System.DateTime activation_start { get; set; }
        public System.DateTime activation_end { get; set; }
        public int leader_ending_status { get; set; }
    }
}
