//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ledger_shares
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public long order_id { get; set; }
        public long top_up_id { get; set; }
        public int gift_id { get; set; }
        public int event_id { get; set; }
        public int event_vinner_id { get; set; }
        public int event_participatore_id { get; set; }
        public int gift_receiver_user_id { get; set; }
        public int gift_sender_user_id { get; set; }
        public int cash_back_id { get; set; }
        public decimal payment_gateway_share { get; set; }
        public int credit_amount { get; set; }
        public int credit_status { get; set; }
        public int credit_type { get; set; }
        public string message { get; set; }
        public string remark { get; set; }
        public System.DateTime created { get; set; }
        public int status { get; set; }
        public int user_bean_balance { get; set; }
        public int user_gold_balance { get; set; }
    }
}
