//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofConversation
    {
        public long conversationID { get; set; }
        public string room { get; set; }
        public sbyte isExternal { get; set; }
        public long startDate { get; set; }
        public long lastActivity { get; set; }
        public int messageCount { get; set; }
    }
}
