//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofMessageArchive
    {
        public long conversationID { get; set; }
        public string fromJID { get; set; }
        public string fromJIDResource { get; set; }
        public string toJID { get; set; }
        public string toJIDResource { get; set; }
        public long sentDate { get; set; }
        public string body { get; set; }
    }
}
