//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofMucRoom
    {
        public long serviceID { get; set; }
        public long roomID { get; set; }
        public string creationDate { get; set; }
        public string modificationDate { get; set; }
        public string name { get; set; }
        public string naturalName { get; set; }
        public string description { get; set; }
        public string lockedDate { get; set; }
        public string emptyDate { get; set; }
        public sbyte canChangeSubject { get; set; }
        public int maxUsers { get; set; }
        public sbyte publicRoom { get; set; }
        public sbyte moderated { get; set; }
        public sbyte membersOnly { get; set; }
        public sbyte canInvite { get; set; }
        public string roomPassword { get; set; }
        public sbyte canDiscoverJID { get; set; }
        public sbyte logEnabled { get; set; }
        public string subject { get; set; }
        public sbyte rolesToBroadcast { get; set; }
        public sbyte useReservedNick { get; set; }
        public sbyte canChangeNick { get; set; }
        public sbyte canRegister { get; set; }
    }
}
