//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofOffline
    {
        public string username { get; set; }
        public long messageID { get; set; }
        public string creationDate { get; set; }
        public int messageSize { get; set; }
        public string stanza { get; set; }
    }
}
