//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofPubsubItem
    {
        public string serviceID { get; set; }
        public string nodeID { get; set; }
        public string id { get; set; }
        public string jid { get; set; }
        public string creationDate { get; set; }
        public string payload { get; set; }
    }
}
