//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofPubsubSubscription
    {
        public string serviceID { get; set; }
        public string nodeID { get; set; }
        public string id { get; set; }
        public string jid { get; set; }
        public string owner { get; set; }
        public string state { get; set; }
        public sbyte deliver { get; set; }
        public sbyte digest { get; set; }
        public int digest_frequency { get; set; }
        public string expire { get; set; }
        public sbyte includeBody { get; set; }
        public string showValues { get; set; }
        public string subscriptionType { get; set; }
        public sbyte subscriptionDepth { get; set; }
        public string keyword { get; set; }
    }
}
