//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofPubsubNode
    {
        public string serviceID { get; set; }
        public string nodeID { get; set; }
        public sbyte leaf { get; set; }
        public string creationDate { get; set; }
        public string modificationDate { get; set; }
        public string parent { get; set; }
        public sbyte deliverPayloads { get; set; }
        public Nullable<int> maxPayloadSize { get; set; }
        public Nullable<sbyte> persistItems { get; set; }
        public Nullable<int> maxItems { get; set; }
        public sbyte notifyConfigChanges { get; set; }
        public sbyte notifyDelete { get; set; }
        public sbyte notifyRetract { get; set; }
        public sbyte presenceBased { get; set; }
        public sbyte sendItemSubscribe { get; set; }
        public string publisherModel { get; set; }
        public sbyte subscriptionEnabled { get; set; }
        public sbyte configSubscription { get; set; }
        public string accessModel { get; set; }
        public string payloadType { get; set; }
        public string bodyXSLT { get; set; }
        public string dataformXSLT { get; set; }
        public string creator { get; set; }
        public string description { get; set; }
        public string language { get; set; }
        public string name { get; set; }
        public string replyPolicy { get; set; }
        public string associationPolicy { get; set; }
        public Nullable<int> maxLeafNodes { get; set; }
    }
}
