//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofRoster
    {
        public long rosterID { get; set; }
        public string username { get; set; }
        public string jid { get; set; }
        public sbyte sub { get; set; }
        public sbyte ask { get; set; }
        public sbyte recv { get; set; }
        public string nick { get; set; }
    }
}
