//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofSecurityAuditLog
    {
        public long msgID { get; set; }
        public string username { get; set; }
        public long entryStamp { get; set; }
        public string summary { get; set; }
        public string node { get; set; }
        public string details { get; set; }
    }
}
