//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofUser
    {
        public string username { get; set; }
        public string plainPassword { get; set; }
        public string encryptedPassword { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string creationDate { get; set; }
        public string modificationDate { get; set; }
    }
}
