//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public long id { get; set; }
        public int user_id { get; set; }
        public int top_up_id { get; set; }
        public decimal price { get; set; }
        public string phone { get; set; }
        public int get_bean { get; set; }
        public int percentage_on_price { get; set; }
        public string transaction_id { get; set; }
        public string status { get; set; }
        public string ip_address { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
    }
}
