//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int id { get; set; }
        public int status { get; set; }
        public string address { get; set; }
        public int user_id { get; set; }
        public int gift_id { get; set; }
        public string gift_sender_display_name { get; set; }
        public int gift_sender_id { get; set; }
        public int gift_resiver_id { get; set; }
        public string gift_resiver_display_name { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string sp_title { get; set; }
        public string sp_description { get; set; }
        public string zh_title { get; set; }
        public string zh_description { get; set; }
        public int media_type { get; set; }
        public string media_image { get; set; }
        public string media_video { get; set; }
        public long comment_count { get; set; }
        public long post_like_count { get; set; }
        public int is_gift_post { get; set; }
        public int gift_sender_reciver_id { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public System.TimeSpan time { get; set; }
        public System.DateTime created { get; set; }
    }
}
