//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class save_push_notifications
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int resiver_user_id { get; set; }
        public int notification_status { get; set; }
        public int notification_type { get; set; }
        public int thanks_id { get; set; }
        public string message { get; set; }
        public int status { get; set; }
        public System.DateTime created { get; set; }
    }
}
