//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class send_gifts
    {
        public int id { get; set; }
        public int vipgift_id { get; set; }
        public int gift_id { get; set; }
        public int gift_weight { get; set; }
        public int gift_amount_gold { get; set; }
        public int gift_amount_bean { get; set; }
        public int user_id { get; set; }
        public int receiver_user_id { get; set; }
        public string description { get; set; }
        public int is_post { get; set; }
        public int amount_type { get; set; }
        public System.DateTime created { get; set; }
    }
}
