//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thank
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int reciver_user_id { get; set; }
        public int save_push_notification_id { get; set; }
        public System.DateTime created { get; set; }
    }
}
