//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public int role_id { get; set; }
        public Nullable<int> ref_id { get; set; }
        public int referral_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string display_name { get; set; }
        public string email { get; set; }
        public Nullable<int> email_verified { get; set; }
        public string email_token { get; set; }
        public string paypal_email { get; set; }
        public string image { get; set; }
        public string user_image { get; set; }
        public string gender { get; set; }
        public System.DateTime dob { get; set; }
        public string fb_id { get; set; }
        public string interested_in { get; set; }
        public string nationality { get; set; }
        public int type { get; set; }
        public string device_udid { get; set; }
        public string device_token { get; set; }
        public string device_type { get; set; }
        public string token { get; set; }
        public int facebook_account { get; set; }
        public int twitter_account { get; set; }
        public int instagram_account { get; set; }
        public int notification { get; set; }
        public int nearby_feature { get; set; }
        public int searchable { get; set; }
        public int notification_sound { get; set; }
        public int hide_message_details { get; set; }
        public int voice_call { get; set; }
        public int video_call { get; set; }
        public int messaging { get; set; }
        public int language { get; set; }
        public int follow_count { get; set; }
        public int gift_received_count { get; set; }
        public int gift_sent_count { get; set; }
        public int total_gold { get; set; }
        public int total_bean { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string address { get; set; }
        public int status { get; set; }
        public int login_logout_status { get; set; }
        public System.DateTime created { get; set; }
    }
}
