//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class verification
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string code { get; set; }
        public System.DateTime validation_time { get; set; }
        public bool is_valid { get; set; }
    }
}
