//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsterBackendAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vipgift
    {
        public int id { get; set; }
        public int status { get; set; }
        public string name_en { get; set; }
        public int gift_weight { get; set; }
        public string image { get; set; }
        public string sound_en { get; set; }
        public string cost_bean { get; set; }
        public string receiver_gold { get; set; }
        public int gift_category_id { get; set; }
        public string name_sp { get; set; }
        public string sound_sp { get; set; }
        public string name_zh { get; set; }
        public string sound_zh { get; set; }
        public System.DateTime created { get; set; }
    }
}
